### ISSUE TITLE
possible new johnoliver sub: r/tijuana

### ISSUE THREAD

**Issue by robertafreese** [username-is-required/reddark-subinfo#249]
Most recent [sticky ](https://old.reddit.com/r/tijuana/comments/14fojt8/meta_adios_goodbye/)(bilingual) announces status johnoliver until June 30.

One post per day, first one confirmed.

**Comment by username-is-required** [comment]
ah, thanks for flagging! i’ll get that one added now.

**Comment by username-is-required** [comment]
> Until 30 June, as my last protest, I will upload a meme of comedian John Oliver every day. The automod bot will automatically delete all comments and posts. This will make the subreddit read only. On the night of 30 June, I shall update the subreddit to be public and delete my account. Enjoy the memes.
